spring.application.name=spring-boot-refresh
spring.datasource.url=jdbc:postgresql://localhost:5332/spring-boot-refresh
spring.datasource.username=pguser
spring.datasource.password=pgpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
